name: Test

on:

  workflow_dispatch:
    inputs:

      name:
        description: Name of the job
        type: string

      image:
        description: Image Name
        type: string

  workflow_call:
    inputs:

      name:
        description: Name of the job
        type: string

      image:
        description: Image Name
        type: string

jobs:

  test:
    name: Test ${{ inputs.name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "Testing ${{ inputs.image }}..."
          sleep $(( $RANDOM % 10 + 1 ))
          echo "Done"
