name: Rebase Bot

on:
  push:
    branches:
      - main

jobs:

  list-pr:

    name: List Pull Requests

    runs-on: ubuntu-latest

    outputs:

      pulls: ${{ steps.list.outputs.pullRequestNumbers }}

    steps:

      - name: GitHub List Pull Requests
        uses: andrea-armstrong/github-list-pull-requests@v1.0.0
        id: list
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          state: open

  rebase:

    name: "Rebase pull request #${{ matrix.pr }}"

    needs: [list-pr]

    runs-on: ubuntu-latest

    strategy:
      matrix:
        pr: ${{ fromJson(needs.list-pr.outputs.pulls) }}

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_NUMBER: ${{ matrix.pr }}

    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure git
        run: |
          git config --global --add safe.directory /github/workspace

      - name: Configure git credentials
        uses: OleksiyRudenko/gha-git-credentials@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ github.actor }}
          actor: ${{ github.actor }}
          email: ${{ github.actor }}@users.noreply.github.com


      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.5
