name: Rebase Bot

on:
  push:
    branches:
      - main

jobs:

  list-pr:

    name: List Pull Requests

    runs-on: ubuntu-latest

    outputs:

      pulls: ${{ steps.list.outputs.pullRequestNumbers }}

    steps:

      - name: GitHub List Pull Requests
        uses: andrea-armstrong/github-list-pull-requests@v1.0.0
        id: list
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          state: open

  rebase:

    name: "Rebase pull request #${{ matrix.pr }}"

    needs: [list-pr]

    runs-on: ubuntu-latest

    strategy:
      matrix:
        pr: ${{ fromJson(needs.list-pr.outputs.pulls) }}

    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ matrix.pr }}

